version: "3"

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
  web:
    container_name: web
    build: .
    command: bash -c "ls && python agrimanager/manage.py runserver 0.0.0.0:8000 | python agrimanager/manage.py migrate"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
