version: "3"

services:
  db:
    image: postgres
    #    volumes:
    #      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python agrimanager/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
