# Generated by Django 3.0.5 on 2020-04-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200411_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Acreage',
        ),
    ]
